name: furtime
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  awesome_notifications: ^0.10.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.2.2
  image_network: ^2.5.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  quickalert: ^1.1.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/budol.jpg
    - assets/images/ttalgi.jpg
